### ISSUE TITLE
Update for nixos

### ISSUE THREAD

**Issue by ohAitch** [asssaf/urbit-fakezod-docker-alpine#2]
This repo's Dockerfile unsurprisingly breaks on `apt-get update` in the new nixos-based `assaf/urbit`. I tried just adding `RUN nix-env -iA nixpkgs.python` `RUN nix-env -iA nixpkgs.pexpect` but it couldn't find `nix-env` either; I fear I'm out of my depth here, halp

**Comment by asssaf** [comment]
sorry, I pushed the update to a tag but forgot to push master. It is updated now and you can build using:
```
docker build --build-arg DOCKER_TAG=urbit-os-v1.0.16-nix .
```

**Comment by ohAitch** [comment]
I see there's two `FROM`s one with the tag and one without, is this intentional?

**Comment by asssaf** [comment]
oops, that's a bug

**Comment by asssaf** [comment]
fixed

**Comment by ohAitch** [comment]
At any rate plan `docker -it run asssaf/urbit-fakezod` sure seems to work now, ty!
